project/teams/urls.py
"""
project.teams URL Configuration

"""
from django.conf.urls import url

from .views import (team_list_view,
                    team_detail_view,
                    team_create_view,
                    team_leave_view,
                    team_update_view,
                    request_send_view,
                    request_response_view)

urlpatterns = [
    url(r'^teams/$', team_list_view, name="team_list"),
    url(r'^teams/create/$', team_create_view, name="team_create"),
    url(r'^teams/update/$', team_update_view, name="team_update"),
    url(r'^teams/leave/$', team_leave_view, name="team_leave"),
    url(r'^team/(?P<slug>[-\w]+)/$', team_detail_view, name="team_detail"),
    url(r'^team/(?P<slug>[-\w]+)/request/$', request_send_view, name="request_send"),

    url(r'^request/(?P<pk>\d+)/$', request_response_view, name="request_response"),
]

project/teams/models.py
from django.contrib.auth.models import User
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator, MaxLengthValidator
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify

import bleach
import markdown
import uuid

name_validator = RegexValidator(
    regex=r"[a-zA-Z0-9_\-.: ]+",
    message="Names can contain letters, numbers, dashes, periods, colons, and whitespace."
)


description_length_validator = MaxLengthValidator(2000)


def slug_validator(value):
    slug = slugify(value)
    if not slugify(value):
        raise ValidationError('Please add some more characters to your team name.')
    if Team.objects.filter(slug=slug).exists():
        raise ValidationError('A team with a similar name exists.')


def ascii_validator(value):
    try:
        value.encode('ascii')
    except UnicodeEncodeError:
        raise ValidationError('Team name should contain only ASCII characters.')


class TeamFullException(Exception):
    pass


class Team(models.Model):

    class Meta:
        ordering = ['name']
        get_latest_by = "created"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    slug = models.SlugField(unique=True, null=False)

    name = models.CharField(max_length=50, validators=[name_validator, ascii_validator, slug_validator],
                            help_text="Your team's project name!")
    description = models.TextField(blank=True, validators=[description_length_validator],
                                   help_text="Tell us about your project! Or don't. It's up to you!")
    rendered_description = models.TextField(editable=False)

    members = models.ManyToManyField(User)

    created = models.DateTimeField(auto_now_add=True)

    @models.permalink
    def get_absolute_url(self):
        kwds = {'slug': self.slug}
        return ('team_detail', (), kwds)

    def __str__(self):
        return self.name

    def is_full(self):
        return self.members.count() >= 5

    def add_member(self, user):
        if not self.is_full():
            return self.members.add(user)
        raise TeamFullException()


class Request(models.Model):

    class Meta:
        ordering = ['created']
        get_latest_by = "created"

    team = models.ForeignKey(Team)
    user = models.ForeignKey(User)

    created = models.DateTimeField(auto_now_add=True)

    @models.permalink
    def get_absolute_url(self):
        kwds = {'pk': self.pk}
        return ('request_response', (), kwds)

    def __str__(self):
        return u"Request for {} to join {}".format(self.user.username,
                                                   self.team.name)

@receiver(pre_save, sender=Team)
def team_pre_save(sender, instance, **kwargs):
    """Called before a Team is saved
    - Sets slug according to name
    - Renders description field
    """
    instance.slug = slugify(instance.name)

    rendered = markdown.markdown(instance.description, safe_mode='escape')
    clean_rendered = bleach.clean(rendered,
                                  tags=settings.ALLOWED_HTML_TAGS,
                                  attributes=settings.ALLOWED_HTML_ATTRS)
    instance.rendered_description = clean_rendered

project/templates/base.html
<!DOCTYPE html>
<html>

  {% include "head.html" %}

  <body>

    {% include "navbar.html" %}

    <!-- Begin page content -->
    {% block base_content %}{% endblock %}

    {% include "scripts.html" %}

    {% include "footer.html" %}
  </body>

</html>

project/templates/default.html
{% extends "base.html" %}

{% block base_content %}

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      {% for message in messages %}
      <div{% if message.tags %} class="alert {{ message.tags }} alert-dismissable"{% endif %}>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{ message }}
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      {% block default_content %} {% endblock %}
    </div>
  </div>
</div>

{% endblock %}

project/templates/footer.html
<footer class="footer">
  <div class="container">
    <p class="text-muted text-center">
      Missouri S&amp;T Computer Science&nbsp;&nbsp;|&nbsp;&nbsp;
      325 Computer Science Building, Rolla, MO 65409&nbsp;&nbsp;|&nbsp;&nbsp;
      <a href="&#109;&#097;&#105;&#108;&#116;&#111;:&#104;&#052;&#104;&#064;&#109;&#115;&#116;&#046;&#101;&#100;&#117;">&#104;&#052;&#104;&#064;&#109;&#115;&#116;&#046;&#101;&#100;&#117;</a>
    </p>
  </div>
</footer>

project/templates/head.html
{% load compress %}

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block title %}Hackathon for Humanity{% endblock %}</title>

  {% compress css %}
  <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="/static/css/sticky-footer.css">
  <link rel="stylesheet" type="text/x-scss" href="/static/css/main.scss">
  {% endcompress %}

  <link rel="shortcut icon" href="/static/images/h-gear.ico" />
</head>

project/templates/navbar.html
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <img src="/static/images/h-gear.svg" alt="H4H brand"/>
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-left">
        <li id="home-nav"><a href="/">Home</a></li>
        <li id="about-nav" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About <i class="fa fa-angle-down"></i></a>
          <ul class="dropdown-menu">
            <li><a href="/about/#the-hackathon">The Hackathon</a></li>
            <li><a href="/about/#the-kickoff">The Kickoff</a></li>
            <li><a href="/about/#st-computer-science">S&amp;T Computer Science</a></li>
            <li><a href="/about/#people">People</a></li>
          </ul>
        </li>
        <li id="rules-nav"><a href="/rules/">Rules</a></li>
        <li id="faq-nav"><a href="/faq/">FAQ</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li id="teams-nav"><a href="{% url 'team_list' %}">Teams</a></li>
        <li id="profiles-nav"><a href="{% url 'profile_list' %}">People</a></li>
        <li id="submission-nav"><a href="{% url 'submission_list' %}">My Submissions</a></li>
        {% if user.is_authenticated %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            My H4H
          </a>
          <ul class="dropdown-menu">
            <li><a href="{{ user.profile.get_absolute_url }}"><i class="fa fa-user"></i>&nbsp;&nbsp;{{ user.username }}</a></li>
            <li><a href="{% url 'profile_update' %}"><i class="fa fa-pencil"></i>&nbsp;&nbsp;Update Profile</a></li>
            {% if user.team_set.all.exists %}
            <li role="separator" class="divider"></li>
            {% with users_team=user.team_set.first %}
            {% with request_count=users_team.request_set.all.count %}
            <li>
              <a href="{{ users_team.get_absolute_url }}">
                <i class="fa fa-users"></i>&nbsp;&nbsp;My Team
              </a>
            </li>
            <li>
              <a href="{{ users_team.get_absolute_url }}">
                {% if request_count %}
                <i class="fa fa-envelope text-success"></i>&nbsp;&nbsp;{{ request_count }} Pending Request{{ request_count | pluralize }}
                {% else %}
                <i class="fa fa-envelope"></i>&nbsp;&nbsp;No Pending Requests
                {% endif %}
              </a>
            </li>
            {% endwith %}
            {% endwith %}
            {% endif %}
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'socialaccount_connections' %}">
                <i class="fa fa-google"></i>&nbsp;&nbsp;My Google Accounts</a>
            </li>
            <li><a href="{% url 'account_logout' %}">
                <i class="fa fa-power-off"></i>&nbsp;&nbsp;Logout</a>
            </li>
          </ul>
        </li>
        {% else %}
        <li>
          <a href="{% url 'team_list' %}" role="button">
            My H4H
          </a>
        </li>
        {% endif %}
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

project/templates/scripts.html
{% load static %}
{% load compress %}

{% compress js %}
<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/static/js/drawer.min.js"></script>
<script type="text/coffeescript" src="/static/js/drawer-button.coffee"></script>
{% endcompress %}