project/submission/urls.py
"""
project. URL Configuration

"""
from django.conf.urls import url

from .views import (submission_list_view,
                    submission_submit_video,
                    submission_submit_file)

urlpatterns = [
    url(r'^submissions/$', submission_list_view, name="submission_list"),
    url(r'^submit-video/$', submission_submit_video, name="submit_video"),
    url(r'^submit-file/$', submission_submit_file, name="submit_file"),
]

project/submission/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxLengthValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from project.teams.models import Team

import hashlib
import os
import uuid


def get_file_dir(instance, filename):
    return os.path.join(str(instance.pk), filename)


class VideoSubmission(models.Model):

    class Meta:
        ordering = ['-created']
        get_latest_by = "created"

    team = models.ForeignKey(Team, blank=True, null=True, on_delete=models.SET_NULL)
    submitter = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)
    video_url = models.URLField()

    def __str__(self):
        return self.team.name if self.team else "(No Team)"


class FileSubmission(models.Model):

    class Meta:
        ordering = ['-created']
        get_latest_by = "created"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    team = models.ForeignKey(Team, blank=True, null=True, on_delete=models.SET_NULL)
    submitter = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)
    submission = models.FileField(upload_to=get_file_dir)
    comments = models.TextField(blank=True, validators=[MaxLengthValidator(1000)],
                                help_text="Any last-minute comments? Don't forget you need README!")
    md5sum = models.CharField(max_length=32, blank=True)

    def __str__(self):
        return self.team.name if self.team else "(No Team)"


@receiver(post_save, sender=FileSubmission)
def file_submission_post_save(sender, instance, **kwargs):
    """Called after a FileSubmission is saved
    - Sets the file's MD5 sum if it isn't already set
    """

    if not instance.md5sum:
        filehash = hashlib.md5()
        with open(instance.submission.path) as f:
            for chunk in iter(lambda: f.read(4096), ""):
                filehash.update(chunk)
        instance.md5sum = filehash.hexdigest()
        instance.save()

project/submission/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import FileSubmission, VideoSubmission


class VideoSubmissionForm(forms.ModelForm):

    class Meta:
        model = VideoSubmission
        fields = ['video_url']

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))
        super(VideoSubmissionForm, self).__init__(*args, **kwargs)


class FileSubmissionForm(forms.ModelForm):

    class Meta:
        model = FileSubmission
        fields = ['submission', 'comments']

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))
        super(FileSubmissionForm, self).__init__(*args, **kwargs)

    def clean_submission(self):
        submission = self.cleaned_data.get('submission', False)
        if submission:
            if submission._size > 129 * 1024**2:
                raise forms.ValidationError("Submission file too large ( > 128 MB )")
            return submission
        else:
            raise forms.ValidationError("Couldn't read uploaded zip.")

project/submission/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.views.generic import View, TemplateView
from django.views.generic.edit import CreateView
from .models import FileSubmission, VideoSubmission
from .forms import FileSubmissionForm, VideoSubmissionForm


class RequiresTeamMixin(View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.team_set.all().exists():
            msg = "You must be on a team to make a submission."
            messages.warning(request, msg)
            return redirect('team_list')
        self.team = self.request.user.team_set.first()
        return super(RequiresTeamMixin, self).dispatch(request, *args, **kwargs)


class SubmissionCreateView(RequiresTeamMixin, CreateView):
    template_name = "submission/submission_create.html"

    def get_initial(self):
        return {'team': self.team}

    def form_valid(self, form):
        submission = form.save(commit=False)
        submission.team = self.team
        submission.submitter = self.request.user
        submission.save()

        for member in self.team.members.all():
            subject = 'New H4H submission!'
            message = render_to_string("submission/submission_email.txt",
                                       context={'submission': submission,
                                                'recipient': member})

            send_mail(subject, message, settings.EMAIL_HOST_USER,
                      [member.email], fail_silently=False)

        return redirect('submission_list')


class SubmissionListView(RequiresTeamMixin, TemplateView):
    template_name = "submission/submission_list.html"

    def get_context_data(self, **kwargs):
        context = super(SubmissionListView, self).get_context_data(**kwargs)
        context['team'] = self.team
        return context


class FileSubmissionCreateView(SubmissionCreateView):
    model = FileSubmission
    form_class = FileSubmissionForm


class VideoSubmissionCreateView(SubmissionCreateView):
    model = VideoSubmission
    form_class = VideoSubmissionForm


submission_list_view = login_required(SubmissionListView.as_view())
submission_submit_file = login_required(FileSubmissionCreateView.as_view())
submission_submit_video = login_required(VideoSubmissionCreateView.as_view())

project/submission/templates/submission/submission_create.html
{% extends "default.html" %}
{% load crispy_forms_tags %}

{% block default_content %}
<div class="jumbotron">
  <h1 style="display:inline;">New Submission</h1>
</div>

{% crispy form %}

{% endblock %}

project/submission/templates/submission/submission_list.html
{% extends "default.html" %}
{% load file_tags %}

{% block default_content %}
<div class="jumbotron">
  <h1>Team Submissions</h1>
  <p>
    <a class="btn btn-success" href="{% url 'submit_video' %}">
      <i class="fa fa-file-video-o"></i>&nbsp;&nbsp;Submit&nbsp;Video
    </a>
    <a class="btn btn-success" href="{% url 'submit_file' %}">
      <i class="fa fa-file-zip-o"></i>&nbsp;&nbsp;Submit&nbsp;File
    </a>
  </p>
</div>

<div class="row">
  <h2>File Submissions</h2>
  <div class="col-xs-12">
    <table class="table">
      <thead>
        <tr>
          <th>Time</th>
          <th>Name</th>
          <th>Submitter</th>
          <th>Size</th>
          <th>MD5 Checksum</th>
        </tr>
      </thead>
      <tbody>
        {% for file in team.filesubmission_set.all %}
        <tr class="{% if forloop.first %}success{% endif %}">
          <th scope="row">{{ file.created }}</th>
          <td>{{ file.submission.file.name | basename }}</td>
          <td>{{ file.submitter }}</td>
          <td>{{ file.submission.file.size | sizeof }}</td>
          <td>{{ file.md5sum }}</td>
        </tr>
        {% empty %}
        <tr>
          <td>No submissions yet.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <h2>Video Submissions</h2>
  <div class="col-xs-12">
    <table class="table">
      <thead>
        <tr>
          <th>Time</th>
          <th>Submitter</th>
          <th>Video URL</th>
        </tr>
      </thead>
      <tbody>
        {% for video in team.videosubmission_set.all %}
        <tr class="{% if forloop.first %}success{% endif %}">
          <th scope="row">{{ video.created }}</th>
          <td>{{ video.submitter }}</td>
          <td>{{ video.video_url }}</td>
        </tr>
        {% empty %}
        <tr>
          <td>No submissions yet.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}